### PR TITLE
Quoted keyword "coveralls": generates warning.

### PR DESCRIPTION
**Pull request by versilov**

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks! This repo 100% needs some refactoring.
I have not used it in a while, I guess a lot of things have changed.

Like: new elixir versions, `mix format`, new `ueberauth` versions, etc.
Do you want to help with these tasks? 🙂 
I am looking for maintainers!

**Comment by versilov** [comment]
I will pull requests for minor issues that generate warnings and irritate me.
Cannot be a good maintainer now — I've got my own baby without an eye, you know:)

**Comment by sobolevn** [comment]
No problem, thanks for your help!

**Comment by versilov** [comment]
Could you please re-run Travis (it should succeed now) or merge the commit?

**Comment by versilov** [comment]
Thanks!

**Pull request merged**
